### ISSUE TITLE
do you have somewhere Sparse fused lasso code for logistric regression

### ISSUE THREAD

**Issue by Sandy4321** [amkatrutsa/liboptpy#5]
thanks for great code
do you have somewhere Sparse fused lasso code for logistric regression like 

http://statweb.stanford.edu/~bjk/regreg/fusedtutorial.html

**Comment by amkatrutsa** [comment]
No, I did not implement it, but you can implement the objective function and its (sub)gradient and then use any of the appropriate methods implemented in this library like subgradient descent or proximal-type methods. 
Examples of using this library for particular optimization problems you can find [here](https://github.com/amkatrutsa/liboptpy/blob/master/examples/demo_unconstr_solvers.ipynb).

**Comment by Sandy4321** [comment]
are sure it is so easy 
seen this link
https://stats.stackexchange.com/questions/364323/solving-linear-regression-with-fused-lasso-regularization-by-mle
After some research I have found out that there is no closed form solution for this problem (and therefore no MLE in particular). A (fast) solution for this problem has been proposed via solution paths, the algorithm can be found here.
??

**Comment by amkatrutsa** [comment]
Well, probably there exists specific methods for this particular problem, but you also can use any general-purpose solvers if the efficiency is not crucial.
