### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Piyushi-0** [amkatrutsa/liboptpy#6]
Hi, Thanks for making the repository publicly available. Please help me resolve the following doubt-

I think the first argument to be passed in the get_stepsize function(ref: line 30 in _proj_gd.py) should be -(self._grad_mem[-1]).
`    def get_stepsize(self):
        return self._step_size.get_stepsize(self._grad_mem[-1], self.convergence[-1], len(self.convergence))
    `

I think so because the first argument of the get_stepsize function seems to correspond to the direction of descent. Please let me know if my understanding is correct.

**Comment by amkatrutsa** [comment]
Hello!
Yes, you are right, thanks for reporting this issue! I have fixed it, please check out the updated version.
